version: "3"
services:
  db: 
    image: mysql:latest
    container_name: db
    #network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=sff
    #command: --default-authentication-plugin=mysql_native_password
  
  app:
    #image: sales-force-backend
    build: .
    container_name: app
    ports:
      - 1115:5000
    environment:
      - MYSQL_ROOT_PASSWORD=sff
      - MYSQL_PORT=3306
      - DEBUG=True
      - FLASK_ENV=development
      - FLASK_APP=sff
      - MYSQL_HOST=db
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    command: flask run --host=0.0.0.0
    depends_on:
      - db
    volumes:
      - ./src:/opt/sff

